//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by slimvdi.rc
//
#define LANG_NEUTRAL                    0x00
#define SUBLANG_NEUTRAL                 0x00
#define HDS_HORZ                        0x0000
#define TBS_HORZ                        0x0000
#define TBS_BOTTOM                      0x0000
#define TBS_RIGHT                       0x0000
#define LVS_ICON                        0x0000
#define LVS_ALIGNTOP                    0x0000
#define TCS_TABS                        0x0000
#define TCS_SINGLELINE                  0x0000
#define TCS_RIGHTJUSTIFY                0x0000
#define DTS_SHORTDATEFORMAT             0x0000
#define PGS_VERT                        0x00000000
#define IDS_NULL                        0
#define IDOK                            1
#define VK_LBUTTON                      0x01
#define LANG_ARABIC                     0x01
#define SUBLANG_DEFAULT                 0x01
#define SUBLANG_ARABIC                  0x01
#define SUBLANG_CHINESE_TRADITIONAL     0x01
#define SUBLANG_DUTCH                   0x01
#define SUBLANG_ENGLISH_US              0x01
#define SUBLANG_FRENCH                  0x01
#define SUBLANG_GERMAN                  0x01
#define SUBLANG_ITALIAN                 0x01
#define SUBLANG_KOREAN                  0x01
#define SUBLANG_NORWEGIAN_BOKMAL        0x01
#define SUBLANG_PORTUGUESE_BRAZILIAN    0x01
#define SUBLANG_SPANISH                 0x01
#define VS_VERSION_INFO                 1
#define VFFF_ISSHAREDFILE               0x0001
#define VFF_CURNEDEST                   0x0001
#define VIFF_FORCEINSTALL               0x0001
#define TTS_ALWAYSTIP                   0x01
#define TBS_AUTOTICKS                   0x0001
#define UDS_WRAP                        0x0001
#define PBS_SMOOTH                      0x01
#define LVS_REPORT                      0x0001
#define TVS_HASBUTTONS                  0x0001
#define TCS_SCROLLOPPOSITE              0x0001
#define ACS_CENTER                      0x0001
#define MCS_DAYSTATE                    0x0001
#define DTS_UPDOWN                      0x0001
#define PGS_HORZ                        0x00000001
#define NFS_EDIT                        0x0001
#define IDS_OK                          1
#define IDCANCEL                        2
#define VK_RBUTTON                      0x02
#define LANG_BULGARIAN                  0x02
#define SUBLANG_SYS_DEFAULT             0x02
#define SUBLANG_ARABIC_IRAQ             0x02
#define SUBLANG_CHINESE_SIMPLIFIED      0x02
#define SUBLANG_DUTCH_BELGIAN           0x02
#define SUBLANG_ENGLISH_UK              0x02
#define SUBLANG_FRENCH_BELGIAN          0x02
#define SUBLANG_GERMAN_SWISS            0x02
#define SUBLANG_ITALIAN_SWISS           0x02
#define SUBLANG_KOREAN_JOHAB            0x02
#define SUBLANG_NORWEGIAN_NYNORSK       0x02
#define SUBLANG_PORTUGUESE              0x02
#define SUBLANG_SPANISH_MEXICAN         0x02
#define VFF_FILEINUSE                   0x0002
#define VIFF_DONTDELETEOLD              0x0002
#define HDS_BUTTONS                     0x0002
#define TTS_NOPREFIX                    0x02
#define TBS_VERT                        0x0002
#define UDS_SETBUDDYINT                 0x0002
#define LVS_SMALLICON                   0x0002
#define TVS_HASLINES                    0x0002
#define TCS_BOTTOM                      0x0002
#define TCS_RIGHT                       0x0002
#define ACS_TRANSPARENT                 0x0002
#define MCS_MULTISELECT                 0x0002
#define DTS_SHOWNONE                    0x0002
#define PGS_AUTOSCROLL                  0x00000002
#define NFS_STATIC                      0x0002
#define MAJOR_VER_DECIMAL               2
#define IDS_NONE                        2
#define IDABORT                         3
#define VK_CANCEL                       0x03
#define LANG_CATALAN                    0x03
#define SUBLANG_ARABIC_EGYPT            0x03
#define SUBLANG_CHINESE_HONGKONG        0x03
#define SUBLANG_ENGLISH_AUS             0x03
#define SUBLANG_FRENCH_CANADIAN         0x03
#define SUBLANG_GERMAN_AUSTRIAN         0x03
#define SUBLANG_SPANISH_MODERN          0x03
#define LVS_LIST                        0x0003
#define LVS_TYPEMASK                    0x0003
#define IDS_ERROR                       3
#define IDRETRY                         4
#define VK_MBUTTON                      0x04
#define LANG_CHINESE                    0x04
#define SUBLANG_ARABIC_LIBYA            0x04
#define SUBLANG_CHINESE_SINGAPORE       0x04
#define SUBLANG_ENGLISH_CAN             0x04
#define SUBLANG_FRENCH_SWISS            0x04
#define SUBLANG_GERMAN_LUXEMBOURG       0x04
#define SUBLANG_SPANISH_GUATEMALA       0x04
#define VFF_BUFFTOOSMALL                0x0004
#define HDS_HOTTRACK                    0x0004
#define TBS_TOP                         0x0004
#define TBS_LEFT                        0x0004
#define UDS_ALIGNRIGHT                  0x0004
#define PBS_VERTICAL                    0x04
#define LVS_SINGLESEL                   0x0004
#define TVS_LINESATROOT                 0x0004
#define TCS_MULTISELECT                 0x0004
#define ACS_AUTOPLAY                    0x0004
#define MCS_WEEKNUMBERS                 0x0004
#define DTS_LONGDATEFORMAT              0x0004
#define PGS_DRAGNDROP                   0x00000004
#define NFS_LISTCOMBO                   0x0004
#define IDS_UNKERROR                    4
#define IDIGNORE                        5
#define LANG_CZECH                      0x05
#define SUBLANG_ARABIC_ALGERIA          0x05
#define SUBLANG_ENGLISH_NZ              0x05
#define SUBLANG_FRENCH_LUXEMBOURG       0x05
#define SUBLANG_GERMAN_LIECHTENSTEIN    0x05
#define SUBLANG_SPANISH_COSTARICA       0x05
#define IDS_NOYES                       5
#define IDYES                           6
#define LANG_DANISH                     0x06
#define SUBLANG_ARABIC_MOROCCO          0x06
#define SUBLANG_ENGLISH_EIRE            0x06
#define SUBLANG_SPANISH_PANAMA          0x06
#define IDNO                            7
#define LANG_GERMAN                     0x07
#define SUBLANG_ARABIC_TUNISIA          0x07
#define SUBLANG_ENGLISH_SAFRICA         0x07
#define SUBLANG_SPANISH_DOMINICAN       0x07
#define IDCLOSE                         8
#define VK_BACK                         0x08
#define LANG_GREEK                      0x08
#define SUBLANG_ARABIC_OMAN             0x08
#define SUBLANG_ENGLISH_JAMAICA         0x08
#define SUBLANG_SPANISH_VENEZUELA       0x08
#define HDS_HIDDEN                      0x0008
#define TBS_BOTH                        0x0008
#define UDS_ALIGNLEFT                   0x0008
#define LVS_SHOWSELALWAYS               0x0008
#define TVS_EDITLABELS                  0x0008
#define TCS_FLATBUTTONS                 0x0008
#define ACS_TIMER                       0x0008
#define MCS_NOTODAYCIRCLE               0x0008
#define NFS_BUTTON                      0x0008
#define IDHELP                          9
#define VK_TAB                          0x09
#define LANG_ENGLISH                    0x09
#define SUBLANG_ARABIC_YEMEN            0x09
#define SUBLANG_ENGLISH_CARRIBEAN       0x09
#define SUBLANG_SPANISH_COLOMBIA        0x09
#define DTS_TIMEFORMAT                  0x0009
#define LANG_SPANISH                    0x0a
#define MINOR_VER_DECIMAL               10
#define LANG_FINNISH                    0x0b
#define VK_CLEAR                        0x0C
#define LANG_FRENCH                     0x0c
#define VK_RETURN                       0x0D
#define LANG_HEBREW                     0x0D
#define LANG_HUNGARIAN                  0x0e
#define LANG_ICELANDIC                  0x0f
#define VK_SHIFT                        0x10
#define LANG_ITALIAN                    0x10
#define SUBLANG_ARABIC_SYRIA            0x10
#define SUBLANG_SPANISH_PERU            0x10
#define TBS_NOTICKS                     0x0010
#define UDS_AUTOBUDDY                   0x0010
#define LVS_SORTASCENDING               0x0010
#define TVS_DISABLEDRAGDROP             0x0010
#define TCS_FORCEICONLEFT               0x0010
#define MCS_NOTODAY                     0x0010
#define DTS_APPCANPARSE                 0x0010
#define NFS_ALL                         0x0010
#define VK_CONTROL                      0x11
#define LANG_JAPANESE                   0x11
#define SUBLANG_ARABIC_JORDAN           0x11
#define SUBLANG_SPANISH_ARGENTINA       0x11
#define VK_MENU                         0x12
#define LANG_KOREAN                     0x12
#define SUBLANG_ARABIC_LEBANON          0x12
#define SUBLANG_SPANISH_ECUADOR         0x12
#define VK_PAUSE                        0x13
#define LANG_DUTCH                      0x13
#define SUBLANG_ARABIC_KUWAIT           0x13
#define SUBLANG_SPANISH_CHILE           0x13
#define VK_CAPITAL                      0x14
#define LANG_NORWEGIAN                  0x14
#define SUBLANG_ARABIC_UAE              0x14
#define SUBLANG_SPANISH_URUGUAY         0x14
#define IDS_DLG_SLIMVDI                20
#define LANG_POLISH                     0x15
#define SUBLANG_ARABIC_BAHRAIN          0x15
#define SUBLANG_SPANISH_PARAGUAY        0x15
#define IDS_DLG_ALT_PROGRESS            21
#define LANG_PORTUGUESE                 0x16
#define SUBLANG_ARABIC_QATAR            0x16
#define SUBLANG_SPANISH_BOLIVIA         0x16
#define IDS_DLG_PARTINFO                22
#define IDS_DLG_VDI_HDR_INFO            23
#define LANG_ROMANIAN                   0x18
#define IDS_DLG_VHD_HDR_INFO            24
#define LANG_RUSSIAN                    0x19
#define IDS_DLG_HDD_HDR_INFO            25
#define LANG_CROATIAN                   0x1a
#define IDS_DLG_VMDK_HDR_INFO           26
#define VK_ESCAPE                       0x1B
#define LANG_SLOVAK                     0x1b
#define IDS_DLG_WRITE_SECTORS           27
#define LANG_ALBANIAN                   0x1c
#define IDS_DLG_ALT_SECTOR_VIEWER       28
#define LANG_SWEDISH                    0x1d
#define LANG_THAI                       0x1e
#define LANG_TURKISH                    0x1f
#define VK_SPACE                        0x20
#define TBS_ENABLESELRANGE              0x0020
#define UDS_ARROWKEYS                   0x0020
#define LVS_SORTDESCENDING              0x0020
#define TVS_SHOWSELALWAYS               0x0020
#define TCS_FORCELABELLEFT              0x0020
#define DTS_RIGHTALIGN                  0x0020
#define VK_PRIOR                        0x21
#define LANG_INDONESIAN                 0x21
#define VK_NEXT                         0x22
#define LANG_UKRAINIAN                  0x22
#define VK_END                          0x23
#define LANG_BYELORUSSIAN               0x23
#define VK_HOME                         0x24
#define LANG_SLOVENIAN                  0x24
#define VK_LEFT                         0x25
#define LANG_ESTONIAN                   0x25
#define VK_UP                           0x26
#define LANG_LATVIAN                    0x26
#define VK_RIGHT                        0x27
#define LANG_LITHUANIAN                 0x27
#define VK_DOWN                         0x28
#define VK_SELECT                       0x29
#define LANG_FARSI                      0x29
#define VK_PRINT                        0x2A
#define VK_EXECUTE                      0x2B
#define VK_SNAPSHOT                     0x2C
#define VK_INSERT                       0x2D
#define LANG_BASQUE                     0x2d
#define VK_DELETE                       0x2E
#define LANG_SORBIAN                    0x2e
#define VK_HELP                         0x2F
#define LANG_AFRIKAANS                  0x36
#define LANG_FAEROESE                   0x38
#define HDS_DRAGDROP                    0x0040
#define TBS_FIXEDLENGTH                 0x0040
#define UDS_HORZ                        0x0040
#define LVS_SHAREIMAGELISTS             0x0040
#define TVS_RTLREADING                  0x0040
#define TCS_HOTTRACK                    0x0040
#define VK_LWIN                         0x5B
#define VK_RWIN                         0x5C
#define VK_APPS                         0x5D
#define VK_NUMPAD0                      0x60
#define VK_NUMPAD1                      0x61
#define VK_NUMPAD2                      0x62
#define VK_NUMPAD3                      0x63
#define VK_NUMPAD4                      0x64
#define VS_USER_DEFINED                 100
#define IDS_SLIMVDI                    100
#define IDS_SELECT_SOURCE               100
#define VK_NUMPAD5                      0x65
#define IDS_SRCFILEFILTER               101
#define VK_NUMPAD6                      0x66
#define IDS_SELECT_DEST                 102
#define VK_NUMPAD7                      0x67
#define IDS_DSTFILEFILTER               103
#define VK_NUMPAD8                      0x68
#define IDS_UNKNOWNFS                   104
#define VK_NUMPAD9                      0x69
#define IDS_PLSSELSRC                   105
#define VK_MULTIPLY                     0x6A
#define IDS_NOSRC                       106
#define VK_ADD                          0x6B
#define IDS_ERRAPPWND                   107
#define VK_SEPARATOR                    0x6C
#define VK_SUBTRACT                     0x6D
#define VK_DECIMAL                      0x6E
#define VK_DIVIDE                       0x6F
#define VK_F1                           0x70
#define VK_F2                           0x71
#define VK_F3                           0x72
#define VK_F4                           0x73
#define VK_F5                           0x74
#define VK_F6                           0x75
#define VK_F7                           0x76
#define VK_F8                           0x77
#define VK_F9                           0x78
#define VK_F10                          0x79
#define VK_F11                          0x7A
#define VK_F12                          0x7B
#define VK_F13                          0x7C
#define VK_F14                          0x7D
#define VK_F15                          0x7E
#define VK_F16                          0x7F
#define VK_F17                          0x80
#define HDS_FULLDRAG                    0x0080
#define TBS_NOTHUMB                     0x0080
#define UDS_NOTHOUSANDS                 0x0080
#define LVS_NOLABELWRAP                 0x0080
#define TVS_NOTOOLTIPS                  0x0080
#define TCS_VERTICAL                    0x0080
#define VK_F18                          0x81
#define VK_F19                          0x82
#define VK_F20                          0x83
#define VK_F21                          0x84
#define VK_F22                          0x85
#define VK_F23                          0x86
#define VK_F24                          0x87
#define VK_NUMLOCK                      0x90
#define VK_SCROLL                       0x91
#define IDS_LOMEM                       150
#define IDS_FINDINGUSEDBLKS             151
#define IDS_CLONINGVHD                  152
#define IDS_CLONEWAIT                   153
#define IDS_USERABORT                   154
#define IDS_ORIGINAL                    155
#define IDS_SNAPSHOT                    156
#define IDS_SIZEERR2                    157
#define IDS_SIZEERR3                    158
#define IDS_SIZEERR4                    159
#define IDS_SIZEERR5                    160
#define IDS_BADNUM                      161
#define IDS_ERRRENAME                   162
#define IDS_USAGE00                     200
#define IDS_USAGE01                     201
#define IDS_USAGE02                     202
#define IDS_USAGE03                     203
#define IDS_USAGE04                     204
#define IDS_USAGE05                     205
#define IDS_USAGE06                     206
#define IDS_USAGE07                     207
#define IDS_USAGE08                     208
#define IDS_USAGE09                     209
#define IDS_USAGE10                     210
#define IDS_USAGE11                     211
#define IDS_USAGE12                     212
#define IDS_USAGE13                     213
#define IDS_USAGE14                     214
#define IDS_USAGE15                     215
#define IDS_USAGE16                     216
#define IDS_USAGE17                     217
#define IDS_USAGE18                     218
#define IDS_USAGE19                     219
#define IDS_BANNER0                     220
#define IDS_BANNER1                     221
#define IDS_BANNER2                     222
#define IDS_ARGERR                      223
#define IDS_OPTTWICE                    224
#define IDS_NOFILEN                     225
#define IDS_NODSIZE                     226
#define IDS_UNKOPT                      227
#define IDS_INVOPT                      228
#define IDS_SRCTWICE                    229
#define IDS_NEEDSRC                     230
#define IDS_VOPTOUTPUT                  231
#define IDS_VOPTKEEPUUID                232
#define IDS_VOPTENLARGE                 233
#define IDS_VOPTCOMPACT                 234
#define IDS_VOPTHELP                    235
#define IDS_CHAROPT                     236
#define IDS_CLONEOF                     250
#define RBS_TOOLTIPS                    0x0100
#define SBARS_SIZEGRIP                  0x0100
#define TBS_TOOLTIPS                    0x0100
#define UDS_HOTTRACK                    0x0100
#define LVS_AUTOARRANGE                 0x0100
#define TVS_CHECKBOXES                  0x0100
#define TCS_BUTTONS                     0x0100
#define IDS_SVOFFSET                    270
#define IDS_SVSECTOR                    271
#define IDS_SVDESTFN                    272
#define IDS_SVBINFLT                    273
#define IDS_SVPEVALSS                   274
#define IDS_SVPEVALSW                   275
#define IDS_SVNOSPACE                   276
#define IDS_SVINVPATH                   277
#define IDS_SVACCDEN                    278
#define IDS_SVWRPROT                    280
#define IDS_SVOVERWR                    281
#define IDS_SVEXISTS                    282
#define IDS_SVLOWMEM                    283
#define IDS_SVWRSECT                    284
#define IDS_SVPRCAPT                    285
#define IDS_SVWRERR                     286
#define IDS_SVABORT                     287
#define IDS_DYNAMIC                     310
#define IDS_FIXED                       311
#define IDS_UNDO                        312
#define IDS_DIFFERENCING                313
#define IDS_SET                         314
#define IDS_NOTSET                      315
#define IDS_NOTSPEC                     316
#define IDS_ACCTYPE0                    317
#define IDS_ACCTYPE1                    318
#define IDS_ACCTYPE2                    319
#define IDS_ACCTYPE3                    320
#define IDS_EXTTYPE0                    321
#define IDS_EXTTYPE1                    322
#define IDS_EXTTYPE2                    323
#define IDS_EXTTYPE3                    324
#define IDS_VDNOEXIST                   350
#define IDS_VDERRSHARE                  351
#define IDS_VDERRREAD                   352
#define IDS_VDNOTVDI                    353
#define IDS_VDINVHANDLE                 354
#define IDS_VDNOMEM                     355
#define IDS_VDSEEKRANGE                 356
#define IDS_VDERRFMT                    357
#define IDS_VDERRSEEK                   358
#define IDS_VDBLKMAP                    359
#define IDS_VDNOTVHD                    360
#define IDS_VDNOTVMDK                   361
#define IDS_VDNODESC                    362
#define IDS_VDINVDESC                   363
#define IDS_VDBADVER                    364
#define IDS_VDMISSING                   365
#define IDS_VDERRCOMP                   366
#define IDS_VDNOEXTENT                  367
#define IDS_VDNOTHDD                    368
#define IDS_VWERRPATH                   390
#define IDS_VWEXISTS                    391
#define IDS_VWNOSPACE                   392
#define IDS_VWWRPROT                    393
#define IDS_VWACCDEN                    394
#define IDS_VWNOMEM                     395
#define IDS_VWWRERR                     396
#define IDS_VWBLOCK                     397
#define IDS_VWEXISTSQ                   398
#define IDS_VWEXISTSC                   399
#define RBS_VARHEIGHT                   0x0200
#define LVS_EDITLABELS                  0x0200
#define TVS_TRACKSELECT                 0x0200
#define TCS_MULTILINE                   0x0200
#define SOFTWARE_VERSION                0x0210
#define RBS_BANDBORDERS                 0x0400
#define LVS_OWNERDRAWFIXED              0x0400
#define TVS_SINGLEEXPAND                0x0400
#define TCS_FIXEDWIDTH                  0x0400
#define COPYRIGHT_YEAR                  2012
#define RBS_FIXEDORDER                  0x0800
#define LVS_ALIGNLEFT                   0x0800
#define TVS_INFOTIP                     0x0800
#define TCS_RAGGEDRIGHT                 0x0800
#define LVS_ALIGNMASK                   0x0c00
#define RBS_REGISTERDROP                0x1000
#define LVS_OWNERDATA                   0x1000
#define TVS_FULLROWSELECT               0x1000
#define TCS_FOCUSONBUTTONDOWN           0x1000
#define RBS_AUTOSIZE                    0x2000
#define LVS_NOSCROLL                    0x2000
#define TVS_NOSCROLL                    0x2000
#define TCS_OWNERDRAWFIXED              0x2000
#define RBS_VERTICALGRIPPER             0x4000
#define LVS_NOCOLUMNHEADER              0x4000
#define TVS_NONEVENHEIGHT               0x4000
#define TCS_TOOLTIPS                    0x4000
#define RBS_DBLCLKTOGGLE                0x8000
#define LVS_NOSORTHEADER                0x8000
#define TCS_FOCUSNEVER                  0x8000
#define LVS_TYPESTYLEMASK               0xfc00

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
